version: '3'
services:
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart : always
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
      - "443:443" 
    networks:
      - inception
    restart : always
    volumes:
      - wordpress:/var/www/
  mariadb:
    build: requirements/mariadb/
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    env_file:
      - .env
    restart : always
    volumes:
      - mariadb:/var/lib/mysql

networks:
  inception:

volumes:
 wordpress:
  driver: local
  driver_opts:
   o: bind
   type: ext4
   device: /home/schancho/data/wordpress
 mariadb:
  driver: local
  driver_opts:
   o: bind
   type: ext4
   device: /home/schancho/data/mariadb

